#!/bin/bash

DIR=~/.bedrock

YELLOW="\033[0;33m"
NC='\033[0m'

cleanup () {
  # Cleanup previous versions.
  rm -rf $DIR
}

install () {
  git clone --quiet git@github.com:bedrockio/bedrock-cli.git $DIR > /dev/null
  pushd $DIR > /dev/null
  yarn install > /dev/null
  popd
}

try_profile()
{
  if [ -f "$1" ]; then
    grep -qxF 'export PATH="$HOME/.bedrock/bin:$PATH"' $1 || echo 'export PATH="$HOME/.bedrock/bin:$PATH"' >> $1
  fi
}

link () {
  # Attempt to add to the following shell profiles
  # if the files exist and are not already linked.
  try_profile $HOME/.zshenv
  try_profile $HOME/.bashrc
  try_profile $HOME/.bash_profile
  try_profile $HOME/.config/fish/config.fish

  # Link once for the current shell
  export PATH="$HOME/.bedrock/bin:$PATH"
}


echo -e "${YELLOW}Installing Bedrock...${NC}"
cleanup
install
link

cat <<-EOM

Done!

You can now run Bedrock commands:

Create new project:
bedrock create

EOM
