apiVersion: v1
kind: Service
metadata:
  name: {{name}}-{{service}}-nodeport
  labels:
    name: {{name}}-{{service}}-nodeport
spec:
  type: NodePort
  selector:
    app: {{name}}-{{service}}
  ports:
    - port: 80
      targetPort: {{port}}
      protocol: TCP